### ISSUE TITLE
Typo in env var:  JWT_PUBKICKEY_LOCATION

### ISSUE THREAD

**Issue by tylerauerbeck** [rht-labs/lodestar-backend#101]
https://github.com/rht-labs/lodestar-backend/blob/e3016409adb67c53132b7f4e1de81c4f6ff3efa1/src/main/resources/application.properties#L18

Nothing wrong from a functional perspective -- just would be a bit more clear to get this fixed up in future releases

**Comment by mcanoy** [comment]
fixed with commit 0912ed5582c03259386d7eb51baaa4b452401654
